### ISSUE TITLE
User-Agent possible conflict

### ISSUE THREAD

**Issue by xR2** [T0astBread/onionflare#1]
When I used the addon User-Agent Switcher (by Linder), Cloudflare would never let me pass, regardless of onionflare.

After _switching_ to User-Agent Switcher and Manager (by Ray) I had simply no issues at all.

So here are the block of text you requested (old addon **and** onionflare):

> Host: www.cloudflare.com
User-Agent: Mozilla/5.0 (X11; Linux i586; rv:31.0) Gecko/20100101 Firefox/31.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Cache-Control: max-age=0

And this is how it looks with the new addon **and** onionflare

> Host: www.cloudflare.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Cache-Control: max-age=0
TE: Trailers

**Comment by micaplush** [comment]
Sorry, I haven't seen this earlier! I suppose you're the person from the AMO review.

The user agent string in the first block looks pretty outdated (Firefox version 31). I suppose this is why Cloudflare rejected it. onionflare itself doesn't do anything with the User-Agent header except on Android, so I don't think there's any conflict here.

Still thanks for reporting!
